[pytest]
addopts = --alluredir=reports/allure --clean-alluredir
markers =
    api: тесты, работающие с API
    mock: тесты, использующие моки вместо реальных HTTP-запросов
    test: тест собственного маркера
    ui: тесты, взаимодействующие с UI / браузером
    smoke: базовые быстрые тесты для проверки ключевой функциональности
