[pytest]
addopts = --alluredir=reports/allure --clean-alluredir
markers =
    test: тест собственного маркера
    ui: тесты, взаимодействующие с UI / браузером
    smoke: базовые быстрые тесты для проверки ключевой функциональности
